/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'ionicons';
import '@stencil/router';
import {
  HighchartsModel,
} from './components/chart/options';
import {
  LocationSegments,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface StellarAccordion {
    'label': string;
    'name': string;
    'open': boolean;
    'refresh': () => void;
    'tight': boolean;
  }
  interface StellarAccordionAttributes extends StencilHTMLAttributes {
    'label'?: string;
    'name'?: string;
    'open'?: boolean;
    'tight'?: boolean;
  }

  interface StellarAsset {
    'align': string;
    'ariaLabel': string;
    'block': boolean;
    'language': string;
    'name': string;
    'src': string;
  }
  interface StellarAssetAttributes extends StencilHTMLAttributes {
    'align'?: string;
    'ariaLabel'?: string;
    'block'?: boolean;
    'language'?: string;
    'name'?: string;
    'src'?: string;
  }

  interface WebAudioDebugger {
    'addHistory': (string: History) => void;
    'count': number;
  }
  interface WebAudioDebuggerAttributes extends StencilHTMLAttributes {
    'count'?: number;
  }

  interface WebAudioEffect {
    'attachEffect': (context: any, source: any) => string;
    'axis': string;
    'method': string;
    'midicontroller': number;
    'responds': string;
    'type': string;
    'use': string;
    'value': number;
  }
  interface WebAudioEffectAttributes extends StencilHTMLAttributes {
    'axis'?: string;
    'method'?: string;
    'midicontroller'?: number;
    'responds'?: string;
    'type'?: string;
    'use'?: string;
    'value'?: number;
  }

  interface WebAudioSequencer {
    'autoplay': boolean;
    'custom': Function;
    'name': string;
    'play': () => void;
    'stop': () => void;
    'taps': number;
    'tempo': number;
  }
  interface WebAudioSequencerAttributes extends StencilHTMLAttributes {
    'autoplay'?: boolean;
    'custom'?: Function;
    'name'?: string;
    'taps'?: number;
    'tempo'?: number;
  }

  interface WebAudioSource {
    'assignBuffer': (webAudio: any, buffer: any) => void;
    'effectsvolume': number;
    'gain': (place?: string) => GainNode;
    'getBuffer': () => AudioBuffer;
    'getDuration': () => number;
    'inert': boolean;
    'midichannel': number;
    'midikey': number;
    'name': string;
    'pause': () => void;
    'play': () => void;
    'playing': boolean;
    'prepare': () => void;
    'skipTo': (time: any) => void;
    'src': string;
    'stop': () => void;
    'toggle': () => void;
    'webAudio': () => HTMLElement;
  }
  interface WebAudioSourceAttributes extends StencilHTMLAttributes {
    'effectsvolume'?: number;
    'inert'?: boolean;
    'midichannel'?: number;
    'midikey'?: number;
    'name'?: string;
    'onTimeupdate'?: (event: CustomEvent) => void;
    'playing'?: boolean;
    'src'?: string;
  }

  interface WebAudioVisualizerShader {
    'type': string;
  }
  interface WebAudioVisualizerShaderAttributes extends StencilHTMLAttributes {
    'type'?: string;
  }

  interface WebAudioVisualizer {
    'color': string;
    'connect': (context: AudioContext, destination: any) => this;
    'for': string;
    'height': number;
    'renderer': AnalyserNode;
    'size': number;
    'smoothing': number;
    'type': string|"wave"|"bars"|"webgl";
    'width': number;
  }
  interface WebAudioVisualizerAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'for'?: string;
    'height'?: number;
    'renderer'?: AnalyserNode;
    'size'?: number;
    'smoothing'?: number;
    'type'?: string|"wave"|"bars"|"webgl";
    'width'?: number;
  }

  interface WebAudio {
    'autoplay': Boolean;
    'connect_the_world': () => Promise<boolean>;
    'get_context': () => AudioContext;
    'is_prepared': () => Boolean;
    'midi': Boolean;
    'name': string;
    'source': (name: any) => any;
  }
  interface WebAudioAttributes extends StencilHTMLAttributes {
    'autoplay'?: Boolean;
    'midi'?: Boolean;
    'name'?: string;
  }

  interface StellarAvatar {
    'color': string;
    'initials': string;
    'name': string;
    'processing': boolean;
    'shape': "circle"|"square"|"rectangle"|"diamond"|"hexagon"|"star"|"message";
    'size': string;
    'src': string;
    'tooltip': boolean;
  }
  interface StellarAvatarAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'initials'?: string;
    'name'?: string;
    'processing'?: boolean;
    'shape'?: "circle"|"square"|"rectangle"|"diamond"|"hexagon"|"star"|"message";
    'size'?: string;
    'src'?: string;
    'tooltip'?: boolean;
  }

  interface StellarBlur {
    'horizontal': number;
    'setBlurFilter': () => void;
    'vertical': number;
  }
  interface StellarBlurAttributes extends StencilHTMLAttributes {
    'horizontal'?: number;
    'vertical'?: number;
  }

  interface StellarBreadcrumb {
    'color': string;
    'disabled': boolean;
    'first': boolean;
    'href': string;
    'label': string;
    'last': boolean;
    'target': string;
  }
  interface StellarBreadcrumbAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'disabled'?: boolean;
    'first'?: boolean;
    'href'?: string;
    'label'?: string;
    'last'?: boolean;
    'target'?: string;
  }

  interface StellarBreadcrumbs {
    'color': string;
    'description': string;
    'home': string;
    'icon': string;
    'icon_size': number;
    'icon_src': string;
    'label': string;
  }
  interface StellarBreadcrumbsAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'description'?: string;
    'home'?: string;
    'icon'?: string;
    'icon_size'?: number;
    'icon_src'?: string;
    'label'?: string;
  }

  interface StellarButton {
    /**
    * Sets the button or link as an active state.
    */
    'active': boolean;
    /**
    * Sets the button or link to render at full width to the parent.
    */
    'block': boolean;
    /**
    * Sets the button or link to provide the affordance of a dangerous action.
    */
    'danger': boolean;
    /**
    * Sets the button or link as disabled and not-interactable.
    */
    'disabled': boolean;
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'for': string;
    'ghost': boolean;
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'href': string;
    /**
    * Sets the button or link as a button with only an icon.
    */
    'icon': boolean;
    /**
    * Sets the button or link as an outlined button.
    */
    'invert': boolean;
    /**
    * Sets accessibility options on the buttons
    */
    'label': string;
    /**
    * Sets the name on the button if the button is an input. Allows the button to act as an item in a form.
    */
    'name': string;
    /**
    * Sets the button or link as an outlined button.
    */
    'outline': boolean;
    /**
    * Sets the padding inside of the button. Can be small, medium, or large.
    */
    'padding': string|"small"|"medium"|"large";
    /**
    * Sets the button or link to render as a pill.
    */
    'pill': boolean;
    /**
    * Sets the button or link as processing when clicked.
    */
    'processable': boolean;
    /**
    * Sets the size of the button. Can be tiny, small, medium, or large.
    */
    'size': string|"tiny"|"small"|"medium"|"large";
    /**
    * Allows the button to render for different tags.
    */
    'tag': "button"|"submit"|"link"|"span"|"route-link";
    /**
    * Sets the target on the anchor tag if the button is a link.
    */
    'target': string;
    /**
    * Sets the value on the button if the button is an input.
    */
    'value': string;
  }
  interface StellarButtonAttributes extends StencilHTMLAttributes {
    /**
    * Sets the button or link as an active state.
    */
    'active'?: boolean;
    /**
    * Sets the button or link to render at full width to the parent.
    */
    'block'?: boolean;
    /**
    * Sets the button or link to provide the affordance of a dangerous action.
    */
    'danger'?: boolean;
    /**
    * Sets the button or link as disabled and not-interactable.
    */
    'disabled'?: boolean;
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'for'?: string;
    'ghost'?: boolean;
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'href'?: string;
    /**
    * Sets the button or link as a button with only an icon.
    */
    'icon'?: boolean;
    /**
    * Sets the button or link as an outlined button.
    */
    'invert'?: boolean;
    /**
    * Sets accessibility options on the buttons
    */
    'label'?: string;
    /**
    * Sets the name on the button if the button is an input. Allows the button to act as an item in a form.
    */
    'name'?: string;
    /**
    * Sets the button or link as an outlined button.
    */
    'outline'?: boolean;
    /**
    * Sets the padding inside of the button. Can be small, medium, or large.
    */
    'padding'?: string|"small"|"medium"|"large";
    /**
    * Sets the button or link to render as a pill.
    */
    'pill'?: boolean;
    /**
    * Sets the button or link as processing when clicked.
    */
    'processable'?: boolean;
    /**
    * Sets the size of the button. Can be tiny, small, medium, or large.
    */
    'size'?: string|"tiny"|"small"|"medium"|"large";
    /**
    * Allows the button to render for different tags.
    */
    'tag'?: "button"|"submit"|"link"|"span"|"route-link";
    /**
    * Sets the target on the anchor tag if the button is a link.
    */
    'target'?: string;
    /**
    * Sets the value on the button if the button is an input.
    */
    'value'?: string;
  }

  interface StellarCallout {
    'type': "alert"|"error"|"info"|"success"|"default";
  }
  interface StellarCalloutAttributes extends StencilHTMLAttributes {
    'type'?: "alert"|"error"|"info"|"success"|"default";
  }

  interface StellarCard {
    'flip_card': (e?: UIEvent) => Promise<void>;
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'flip_icon': string;
    /**
    * Let's a card be flippable
    */
    'flippable': boolean;
    /**
    * Renders a flipped card
    */
    'flipped': boolean;
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'for': string;
    /**
    * Sets the href if the card is a link.
    */
    'href': string;
    /**
    * Sets the name if the card is a button.
    */
    'name': string;
    /**
    * Sets the padding inside of the button. Can be small, medium, or large.
    */
    'padding': string|"small"|"medium"|"large";
    /**
    * Renders a shadow on the card
    */
    'shadow': string|"light"|"medium"|"heavy";
    /**
    * Sets the element to render the card as - an anchor tag, a button, or a div.
    */
    'tag': "stencil-route-link"|"a"|"button"|"div";
    'transition': boolean;
    /**
    * Sets the element to render the card as - an anchor tag, a button, or a div.
    */
    'type': string;
    /**
    * Sets the value if the card is a button.
    */
    'value': string;
  }
  interface StellarCardAttributes extends StencilHTMLAttributes {
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'flip_icon'?: string;
    /**
    * Let's a card be flippable
    */
    'flippable'?: boolean;
    /**
    * Renders a flipped card
    */
    'flipped'?: boolean;
    /**
    * Sets the href on the anchor tag if the button is a link.
    */
    'for'?: string;
    /**
    * Sets the href if the card is a link.
    */
    'href'?: string;
    /**
    * Sets the name if the card is a button.
    */
    'name'?: string;
    'onFlip'?: (event: CustomEvent) => void;
    /**
    * Sets the padding inside of the button. Can be small, medium, or large.
    */
    'padding'?: string|"small"|"medium"|"large";
    /**
    * Renders a shadow on the card
    */
    'shadow'?: string|"light"|"medium"|"heavy";
    /**
    * Sets the element to render the card as - an anchor tag, a button, or a div.
    */
    'tag'?: "stencil-route-link"|"a"|"button"|"div";
    'transition'?: boolean;
    /**
    * Sets the element to render the card as - an anchor tag, a button, or a div.
    */
    'type'?: string;
    /**
    * Sets the value if the card is a button.
    */
    'value'?: string;
  }

  interface StellarChart {
    'config': HighchartsModel;
    'for': string;
    'get_options': () => any;
    'options': (newOptions: any) => void;
    'refresh': () => void;
    'remote': string;
    'type': "area"|"areaspline"|"bar"|"bubble"|"column"|"line"|"pie"|"polygon"|"scatter"|"spline"|"waterfall";
  }
  interface StellarChartAttributes extends StencilHTMLAttributes {
    'config'?: HighchartsModel;
    'for'?: string;
    'remote'?: string;
    'type'?: "area"|"areaspline"|"bar"|"bubble"|"column"|"line"|"pie"|"polygon"|"scatter"|"spline"|"waterfall";
  }

  interface StellarCode {
    'clipboard': () => Promise<void>;
    'codeString': string;
    'copy': boolean;
    'expandable': boolean;
    'expanded': boolean;
    'feature': boolean;
    'highlight': () => void;
    'language': string;
    'preview': boolean;
    'result': () => Promise<string>;
    'setCode': (code: any) => void;
    'simple': boolean;
  }
  interface StellarCodeAttributes extends StencilHTMLAttributes {
    'codeString'?: string;
    'copy'?: boolean;
    'expandable'?: boolean;
    'expanded'?: boolean;
    'feature'?: boolean;
    'language'?: string;
    'preview'?: boolean;
    'simple'?: boolean;
  }

  interface StellarColorPicker {
    'val': string;
  }
  interface StellarColorPickerAttributes extends StencilHTMLAttributes {
    'onChange'?: (event: CustomEvent) => void;
    'val'?: string;
  }

  interface StellarComment {
    'content': any;
    'name': any;
  }
  interface StellarCommentAttributes extends StencilHTMLAttributes {
    'content'?: any;
    'name'?: any;
  }

  interface StellarComments {}
  interface StellarCommentsAttributes extends StencilHTMLAttributes {}

  interface StellarContent {
    'behavior': string;
    'for': string;
    'open': boolean;
  }
  interface StellarContentAttributes extends StencilHTMLAttributes {
    'behavior'?: string;
    'for'?: string;
    'open'?: boolean;
  }

  interface CopyWrap {
    'align': string;
    'full': boolean;
  }
  interface CopyWrapAttributes extends StencilHTMLAttributes {
    'align'?: string;
    'full'?: boolean;
  }

  interface StellarDropdown {
    'icon': boolean;
    'label': string;
    'open': boolean;
    'position': "left"|"center"|"right";
  }
  interface StellarDropdownAttributes extends StencilHTMLAttributes {
    'icon'?: boolean;
    'label'?: string;
    'open'?: boolean;
    'position'?: "left"|"center"|"right";
  }

  interface StellarForm {
    'acceptCharset': string;
    'action': string;
    'ajax': boolean;
    'autocomplete': string;
    'enctype': string;
    'method': string;
    'name': string;
    'novalidate': boolean;
    'refresh': () => Promise<void>;
    'register': (selectors: string[]) => Promise<void>;
    'state': () => Promise<{ els: any; json: any; results: FormResult[]; formData: any; valid: boolean; }>;
    'submit_form': () => Promise<void>;
    'target': string;
  }
  interface StellarFormAttributes extends StencilHTMLAttributes {
    'acceptCharset'?: string;
    'action'?: string;
    'ajax'?: boolean;
    'autocomplete'?: string;
    'enctype'?: string;
    'method'?: string;
    'name'?: string;
    'novalidate'?: boolean;
    'onSubmit'?: (event: CustomEvent) => void;
    'target'?: string;
  }

  interface StellarGrid {
    'align': string;
    'cols': number|string;
    'compact': boolean;
    'padding': boolean;
    'refresh': () => Promise<void>;
    'responsive': boolean|string;
    'swappable': boolean;
    'swappableSelector': string;
  }
  interface StellarGridAttributes extends StencilHTMLAttributes {
    'align'?: string;
    'cols'?: number|string;
    'compact'?: boolean;
    'onOrderChanged'?: (event: CustomEvent) => void;
    'padding'?: boolean;
    'responsive'?: boolean|string;
    'swappable'?: boolean;
    'swappableSelector'?: string;
  }

  interface StellarGroupOverflow {
    'count': number;
    'size': string;
  }
  interface StellarGroupOverflowAttributes extends StencilHTMLAttributes {
    'count'?: number;
    'size'?: string;
  }

  interface StellarGroup {
    'count': number;
    'overflow': boolean;
    'size': string;
  }
  interface StellarGroupAttributes extends StencilHTMLAttributes {
    'count'?: number;
    'overflow'?: boolean;
    'size'?: string;
  }

  interface StellarImage {
    'bg': string;
    'height': number;
    'medium': () => Promise<any>;
    'nozoom': boolean;
    'poster': string;
    'width': number;
  }
  interface StellarImageAttributes extends StencilHTMLAttributes {
    'bg'?: string;
    'height'?: number;
    'nozoom'?: boolean;
    'poster'?: string;
    'width'?: number;
  }

  interface StellarInput {
    'accept': string;
    'autocomplete': string;
    'autofocus': boolean;
    'color': string;
    'cols': number;
    'dateType': "month"|"year"|"day";
    /**
    * The pre-set value to pass to the input element
    */
    'default': any;
    'description': string;
    'disabled': boolean;
    'droppable': boolean;
    'files': Array<any>;
    'focused': boolean;
    'getDatePicker': () => Promise<any>;
    'getId': () => Promise<string>;
    'getStrength': () => Promise<object>;
    'icon': boolean;
    'invalid': (message: string | boolean, valid?: boolean, level?: number) => Promise<void>;
    'label': string;
    'match': string;
    'max': number;
    'maxlength': number;
    'min': number;
    'multiple': boolean;
    'multipleFileCaption': string;
    /**
    * The name of the input element
    */
    'name': string;
    'novalidate': boolean;
    'placeholder': string;
    'readonly': boolean;
    'replace_placeholder': string;
    'required': boolean;
    /**
    * The pre-set value to pass to the input element
    */
    'requirements': boolean;
    'rows': number;
    'setStrength': (value: number) => Promise<void>;
    'size': string;
    'spellcheck': boolean;
    'step': number;
    'tokenField': any;
    'tooltip': string;
    /**
    * The kind of element that the Input should be rendered as
    */
    'type': string;
    'val': () => Promise<any>;
    'validate': () => Promise<FormResult>;
    'validates': string;
    /**
    * The pre-set value to pass to the input element
    */
    'value': any;
    'wrap': string;
  }
  interface StellarInputAttributes extends StencilHTMLAttributes {
    'accept'?: string;
    'autocomplete'?: string;
    'autofocus'?: boolean;
    'color'?: string;
    'cols'?: number;
    'dateType'?: "month"|"year"|"day";
    /**
    * The pre-set value to pass to the input element
    */
    'default'?: any;
    'description'?: string;
    'disabled'?: boolean;
    'droppable'?: boolean;
    'files'?: Array<any>;
    'focused'?: boolean;
    'icon'?: boolean;
    'label'?: string;
    'match'?: string;
    'max'?: number;
    'maxlength'?: number;
    'min'?: number;
    'multiple'?: boolean;
    'multipleFileCaption'?: string;
    /**
    * The name of the input element
    */
    'name'?: string;
    'novalidate'?: boolean;
    /**
    * Public: Blur event
    */
    'onBluring'?: (event: CustomEvent) => void;
    /**
    * Public: Changed event
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * Public: Focus event
    */
    'onFocusing'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'replace_placeholder'?: string;
    'required'?: boolean;
    /**
    * The pre-set value to pass to the input element
    */
    'requirements'?: boolean;
    'rows'?: number;
    'size'?: string;
    'spellcheck'?: boolean;
    'step'?: number;
    'tokenField'?: any;
    'tooltip'?: string;
    /**
    * The kind of element that the Input should be rendered as
    */
    'type'?: string;
    'validates'?: string;
    /**
    * The pre-set value to pass to the input element
    */
    'value'?: any;
    'wrap'?: string;
  }

  interface StellarItem {
    'apply': (data: any) => Promise<void>;
    'danger': boolean;
    'data': () => Promise<{ size: string; value: string; type: "stencil-route-link" | "a" | "button"; label: string; danger: boolean; slotted: any; }>;
    'fit': boolean;
    'focused': boolean;
    'history': RouterHistory;
    'href': string;
    'label': string;
    'location': LocationSegments;
    'multiple': boolean;
    'route': boolean;
    'select_item': (state?: { selected: boolean; }) => void;
    'selectable': boolean;
    'selected': boolean;
    'setFocus': () => Promise<void>;
    'simple': boolean;
    'size': string;
    'type': "a"|"button"|"stencil-route-link";
    'value': string;
    'valueLabel': string;
    'wrap': boolean;
  }
  interface StellarItemAttributes extends StencilHTMLAttributes {
    'danger'?: boolean;
    'fit'?: boolean;
    'focused'?: boolean;
    'history'?: RouterHistory;
    'href'?: string;
    'label'?: string;
    'location'?: LocationSegments;
    'multiple'?: boolean;
    'onBlurChanged'?: (event: CustomEvent) => void;
    'onFocusChanged'?: (event: CustomEvent) => void;
    'onMounted'?: (event: CustomEvent) => void;
    'onSelectionChanged'?: (event: CustomEvent) => void;
    'route'?: boolean;
    'selectable'?: boolean;
    'selected'?: boolean;
    'simple'?: boolean;
    'size'?: string;
    'type'?: "a"|"button"|"stencil-route-link";
    'value'?: string;
    'valueLabel'?: string;
    'wrap'?: boolean;
  }

  interface StellarLabel {
    'for': string;
    'size': string;
    'underneath': boolean;
  }
  interface StellarLabelAttributes extends StencilHTMLAttributes {
    'for'?: string;
    'size'?: string;
    'underneath'?: boolean;
  }

  interface StellarLayout {
    'align': "baseline"|"center"|"top"|"bottom";
    'padding': "none"|"tiny"|"small"|"medium"|"large";
    'refresh': () => void;
    'size': "tiny"|"small"|"medium"|"large"|"full"|"flush";
    'type': string;
  }
  interface StellarLayoutAttributes extends StencilHTMLAttributes {
    'align'?: "baseline"|"center"|"top"|"bottom";
    'padding'?: "none"|"tiny"|"small"|"medium"|"large";
    'size'?: "tiny"|"small"|"medium"|"large"|"full"|"flush";
    'type'?: string;
  }

  interface Stellar360Image {
    'height': number;
    'poster': string;
    'src': string;
    'width': number;
  }
  interface Stellar360ImageAttributes extends StencilHTMLAttributes {
    'height'?: number;
    'poster'?: string;
    'src'?: string;
    'width'?: number;
  }

  interface Stellar360Video {
    'height': number;
    'poster': string;
    'src': string;
    'width': number;
  }
  interface Stellar360VideoAttributes extends StencilHTMLAttributes {
    'height'?: number;
    'poster'?: string;
    'src'?: string;
    'width'?: number;
  }

  interface StellarInterviewLine {
    'complement': boolean;
    'in': number;
    'out': number;
  }
  interface StellarInterviewLineAttributes extends StencilHTMLAttributes {
    'complement'?: boolean;
    'in'?: number;
    'out'?: number;
  }

  interface StellarInterview {
    'aspectRatio': number;
    'debug': boolean;
    'height': number;
    'label': string;
    'pause': () => void;
    'play': () => void;
    'playing': boolean;
    'skipTo': (time: number) => void;
    'src': string;
    'toggle': () => void;
    'width': number;
  }
  interface StellarInterviewAttributes extends StencilHTMLAttributes {
    'aspectRatio'?: number;
    'debug'?: boolean;
    'height'?: number;
    'label'?: string;
    'playing'?: boolean;
    'src'?: string;
    'width'?: number;
  }

  interface SkeletonImg {
    'height': number;
    'icon': boolean;
    'loading': boolean;
    'width': number;
  }
  interface SkeletonImgAttributes extends StencilHTMLAttributes {
    'height'?: number;
    'icon'?: boolean;
    'loading'?: boolean;
    'width'?: number;
  }

  interface SkeletonText {
    'as': string|'h1'|'h2'|'h3'|'h4'|'h5'|'h6'|'p';
    'loading': boolean;
    'width': number;
  }
  interface SkeletonTextAttributes extends StencilHTMLAttributes {
    'as'?: string|'h1'|'h2'|'h3'|'h4'|'h5'|'h6'|'p';
    'loading'?: boolean;
    'width'?: number;
  }

  interface StellarVideo {
    'autoplay': boolean;
    'controls': boolean;
    'height': number;
    'muted': boolean;
    'overlay': boolean;
    'playsinline': boolean;
    'poster': string;
    'preload': string;
    'width': number;
  }
  interface StellarVideoAttributes extends StencilHTMLAttributes {
    'autoplay'?: boolean;
    'controls'?: boolean;
    'height'?: number;
    'muted'?: boolean;
    'overlay'?: boolean;
    'playsinline'?: boolean;
    'poster'?: string;
    'preload'?: string;
    'width'?: number;
  }

  interface StellarMessage {
    'closable': boolean;
    'name': string;
    'remember': boolean;
    'shown': boolean;
    'size': "full"|"default";
    'striped': boolean;
    'type': "alert"|"error"|"info"|"success";
  }
  interface StellarMessageAttributes extends StencilHTMLAttributes {
    'closable'?: boolean;
    'name'?: string;
    'remember'?: boolean;
    'shown'?: boolean;
    'size'?: "full"|"default";
    'striped'?: boolean;
    'type'?: "alert"|"error"|"info"|"success";
  }

  interface StellarPagination {
    'color': string;
    'current': number;
    'padding': number;
    /**
    * Public: Sets the max cap of pages you can skip through
    */
    'pages': number;
    'type': "full"|"compact";
    'url': any;
  }
  interface StellarPaginationAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'current'?: number;
    'onChanged'?: (event: CustomEvent) => void;
    'padding'?: number;
    /**
    * Public: Sets the max cap of pages you can skip through
    */
    'pages'?: number;
    'type'?: "full"|"compact";
    'url'?: any;
  }

  interface StellarPasswordRequirements {
    'for': string;
    'size': "tiny"|"small"|"large";
  }
  interface StellarPasswordRequirementsAttributes extends StencilHTMLAttributes {
    'for'?: string;
    'size'?: "tiny"|"small"|"large";
  }

  interface StellarProgress {
    'blurable': boolean;
    /**
    * Allows the progress bar to be clicked on, to help the user to navigate through the progressing content.
    */
    'editable': boolean;
    /**
    * Sets the maximum cap for steps in the progress bar
    */
    'max': number;
    /**
    * eliminates the easing in the css so you can apply value updates without jitter.
    */
    'noease': boolean;
    /**
    * eliminates the easing in the css so you can apply value updates without jitter.
    */
    'rounded': boolean;
    /**
    * Renders if this element is slender or not
    */
    'slender': boolean;
    /**
    * Sets the value of the progress bar
    */
    'value': number;
  }
  interface StellarProgressAttributes extends StencilHTMLAttributes {
    'blurable'?: boolean;
    /**
    * Allows the progress bar to be clicked on, to help the user to navigate through the progressing content.
    */
    'editable'?: boolean;
    /**
    * Sets the maximum cap for steps in the progress bar
    */
    'max'?: number;
    /**
    * eliminates the easing in the css so you can apply value updates without jitter.
    */
    'noease'?: boolean;
    'onValueChange'?: (event: CustomEvent) => void;
    /**
    * eliminates the easing in the css so you can apply value updates without jitter.
    */
    'rounded'?: boolean;
    /**
    * Renders if this element is slender or not
    */
    'slender'?: boolean;
    /**
    * Sets the value of the progress bar
    */
    'value'?: number;
  }

  interface StellarReveal {
    'active': boolean;
    'animation': "fadeIn"|"fadeInUp"|"fadeInDown";
    'delay': number;
    'in': () => Promise<void>;
    'out': () => Promise<void>;
    'outAnimation': "fadeOut"|"fadeOutUp"|"fadeOutDown";
    'timing': number;
  }
  interface StellarRevealAttributes extends StencilHTMLAttributes {
    'active'?: boolean;
    'animation'?: "fadeIn"|"fadeInUp"|"fadeInDown";
    'delay'?: number;
    'outAnimation'?: "fadeOut"|"fadeOutUp"|"fadeOutDown";
    'timing'?: number;
  }

  interface StellarScatter {
    'colors': boolean;
    'float': boolean;
    'max': number;
    'min': number;
    'sizes': boolean;
  }
  interface StellarScatterAttributes extends StencilHTMLAttributes {
    'colors'?: boolean;
    'float'?: boolean;
    'max'?: number;
    'min'?: number;
    'sizes'?: boolean;
  }

  interface StellarSelect {
    'default': any;
    'description': string;
    'focused': boolean;
    'footer': boolean;
    'inline': boolean;
    'label': string;
    'multiple': boolean;
    'name': string|boolean;
    'novalidate': boolean;
    'open': boolean;
    'option_elements': () => Promise<NodeListOf<any>>;
    'options': () => Promise<string[]>;
    'other': boolean;
    'overlay': boolean;
    'placeholder': string;
    'placeholderInverted': boolean;
    'processing': boolean;
    'required': boolean;
    'size': string;
    'tooltip': string;
    'validate': () => Promise<FormResult>;
    'value': Array<string>|string;
    'valueLabel': string;
    'verbiage': string;
    'verbiageAn': boolean;
  }
  interface StellarSelectAttributes extends StencilHTMLAttributes {
    'default'?: any;
    'description'?: string;
    'focused'?: boolean;
    'footer'?: boolean;
    'inline'?: boolean;
    'label'?: string;
    'multiple'?: boolean;
    'name'?: string|boolean;
    'novalidate'?: boolean;
    'onChange'?: (event: CustomEvent) => void;
    'open'?: boolean;
    'other'?: boolean;
    'overlay'?: boolean;
    'placeholder'?: string;
    'placeholderInverted'?: boolean;
    'processing'?: boolean;
    'required'?: boolean;
    'size'?: string;
    'tooltip'?: string;
    'value'?: Array<string>|string;
    'valueLabel'?: string;
    'verbiage'?: string;
    'verbiageAn'?: boolean;
  }

  interface StellarSlide {}
  interface StellarSlideAttributes extends StencilHTMLAttributes {}

  interface StellarSlides {
    'autoHeight': boolean;
    'centeredSlides': boolean;
    'direction': "horizontal"|"vertical";
    'effect': "slide"|"fade"|"cube"|"coverflow"|"flip";
    /**
    * Get the index of the active slide.
    */
    'getActiveIndex': () => Promise<number>;
    /**
    * Get the index of the previous slide.
    */
    'getPreviousIndex': () => Promise<number>;
    /**
    * Get whether or not the current slide is the first slide.
    */
    'isBeginning': () => Promise<boolean>;
    /**
    * Get whether or not the current slide is the last slide.
    */
    'isEnd': () => Promise<boolean>;
    /**
    * Get the total number of slides.
    */
    'length': () => Promise<number>;
    /**
    * Lock or unlock the ability to slide to the next slides.
    */
    'lockSwipeToNext': (shouldLockSwipeToNext: boolean) => Promise<any>;
    /**
    * Lock or unlock the ability to slide to the previous slides.
    */
    'lockSwipeToPrev': (shouldLockSwipeToPrev: boolean) => Promise<any>;
    /**
    * Lock or unlock the ability to slide to change slides.
    */
    'lockSwipes': (shouldLockSwipes: boolean) => Promise<any>;
    'loop': boolean;
    'nested': boolean;
    /**
    * Options to pass to the swiper instance. See http://idangero.us/swiper/api/ for valid options
    */
    'options': any;
    /**
    * Show or hide the pager
    */
    'pager': boolean;
    'pagination': boolean;
    /**
    * Transition to the next slide.
    */
    'slideNext': (speed?: number, runCallbacks?: boolean) => Promise<void>;
    /**
    * Transition to the previous slide.
    */
    'slidePrev': (speed?: number, runCallbacks?: boolean) => Promise<void>;
    /**
    * Transition to the specified slide.
    */
    'slideTo': (index: number, speed?: number, runCallbacks?: boolean) => Promise<void>;
    'slidesPerView': number;
    'spaceBetween': number;
    'speed': number;
    /**
    * Start auto play.
    */
    'startAutoplay': () => void;
    /**
    * Stop auto play.
    */
    'stopAutoplay': () => void;
    /**
    * Update the underlying slider implementation. Call this if you've added or removed child slides.
    */
    'update': () => Promise<void>;
    'watchSlidesProgress': boolean;
    'watchSlidesVisibility': boolean;
  }
  interface StellarSlidesAttributes extends StencilHTMLAttributes {
    'autoHeight'?: boolean;
    'centeredSlides'?: boolean;
    'direction'?: "horizontal"|"vertical";
    'effect'?: "slide"|"fade"|"cube"|"coverflow"|"flip";
    'loop'?: boolean;
    'nested'?: boolean;
    /**
    * Emitted after the active slide has changed.
    */
    'onIonSlideDidChange'?: (event: CustomEvent) => void;
    /**
    * Emitted when the slider is actively being moved.
    */
    'onIonSlideDrag'?: (event: CustomEvent) => void;
    /**
    * Emitted when the next slide has ended.
    */
    'onIonSlideNextEnd'?: (event: CustomEvent) => void;
    /**
    * Emitted when the next slide has started.
    */
    'onIonSlideNextStart'?: (event: CustomEvent) => void;
    /**
    * Emitted when the previous slide has ended.
    */
    'onIonSlidePrevEnd'?: (event: CustomEvent) => void;
    /**
    * Emitted when the previous slide has started.
    */
    'onIonSlidePrevStart'?: (event: CustomEvent) => void;
    /**
    * Emitted when the slider is at the last slide.
    */
    'onIonSlideReachEnd'?: (event: CustomEvent) => void;
    /**
    * Emitted when the slider is at its initial position.
    */
    'onIonSlideReachStart'?: (event: CustomEvent) => void;
    /**
    * Emitted when the user releases the touch.
    */
    'onIonSlideTouchEnd'?: (event: CustomEvent) => void;
    /**
    * Emitted when the user first touches the slider.
    */
    'onIonSlideTouchStart'?: (event: CustomEvent) => void;
    /**
    * Emitted when the slide transition has ended.
    */
    'onIonSlideTransitionEnd'?: (event: CustomEvent) => void;
    /**
    * Emitted when the slide transition has started.
    */
    'onIonSlideTransitionStart'?: (event: CustomEvent) => void;
    /**
    * Emitted before the active slide has changed.
    */
    'onIonSlideWillChange'?: (event: CustomEvent) => void;
    /**
    * Options to pass to the swiper instance. See http://idangero.us/swiper/api/ for valid options
    */
    'options'?: any;
    /**
    * Show or hide the pager
    */
    'pager'?: boolean;
    'pagination'?: boolean;
    'slidesPerView'?: number;
    'spaceBetween'?: number;
    'speed'?: number;
    'watchSlidesProgress'?: boolean;
    'watchSlidesVisibility'?: boolean;
  }

  interface StellarStep {
    'disabled': boolean;
    'href': string;
    'open': boolean;
    'order': number;
    'tabCount': number;
  }
  interface StellarStepAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'href'?: string;
    'onContentChange'?: (event: CustomEvent) => void;
    'open'?: boolean;
    'order'?: number;
    'tabCount'?: number;
  }

  interface StellarSteps {
    'contents': () => any[];
    'name': string;
    'steps': () => any[];
  }
  interface StellarStepsAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface StellarSwitch {
    'activate': () => Promise<void>;
    'checked': boolean;
    'checkedDefault': boolean;
  }
  interface StellarSwitchAttributes extends StencilHTMLAttributes {
    'checked'?: boolean;
    'checkedDefault'?: boolean;
    'onChange'?: (event: CustomEvent) => void;
  }

  interface StellarTab {
    'disabled': boolean;
    'href': string;
    'notifications': boolean|number;
    'open': boolean;
    'order': number;
    'tabCount': number;
    'tag': string;
  }
  interface StellarTabAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'href'?: string;
    'notifications'?: boolean|number;
    'onContentChange'?: (event: CustomEvent) => void;
    'open'?: boolean;
    'order'?: number;
    'tabCount'?: number;
    'tag'?: string;
  }

  interface StellarTable {
    'chart': boolean;
    'name': string;
    'striped': boolean;
    'upgrade': boolean;
  }
  interface StellarTableAttributes extends StencilHTMLAttributes {
    'chart'?: boolean;
    'name'?: string;
    'striped'?: boolean;
    'upgrade'?: boolean;
  }

  interface StellarTabs {
    'behavior': string;
    'block': boolean;
    'blurring': () => void;
    'contents': () => Promise<any[]>;
    'height': string;
    'name': string;
    'noanimation': boolean;
    'size': string|"tiny"|"small"|"medium"|"large";
    'tabs': () => Promise<any[]>;
    'vertical': boolean;
  }
  interface StellarTabsAttributes extends StencilHTMLAttributes {
    'behavior'?: string;
    'block'?: boolean;
    'height'?: string;
    'name'?: string;
    'noanimation'?: boolean;
    'size'?: string|"tiny"|"small"|"medium"|"large";
    'vertical'?: boolean;
  }

  interface StellarTag {
    'color': string;
    'outline': boolean;
    'pill': boolean;
    'size': string;
    'textColor': string;
  }
  interface StellarTagAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'outline'?: boolean;
    'pill'?: boolean;
    'size'?: string;
    'textColor'?: string;
  }

  interface StellarToggleOption {
    'checked': boolean;
    'checkedDefault': boolean;
    'confirm': () => Promise<void>;
    'default': string;
    'disabled': boolean;
    'for': string;
    'icon': boolean;
    'inline': boolean;
    'name': string;
    'required': boolean;
    'selectedCopy': string;
    'single': boolean;
    'size': boolean;
    'tooltip': string;
    'type': string;
    'updateSelected': (value: boolean) => void;
    'value': string;
  }
  interface StellarToggleOptionAttributes extends StencilHTMLAttributes {
    'checked'?: boolean;
    'checkedDefault'?: boolean;
    'default'?: string;
    'disabled'?: boolean;
    'for'?: string;
    'icon'?: boolean;
    'inline'?: boolean;
    'name'?: string;
    'onChange'?: (event: CustomEvent) => void;
    'required'?: boolean;
    'selectedCopy'?: string;
    'single'?: boolean;
    'size'?: boolean;
    'tooltip'?: string;
    'type'?: string;
    'value'?: string;
  }

  interface StellarToggle {
    'card': any;
    'description': string;
    'flip': boolean;
    'label': string;
    'name': string;
    'novalidate': boolean;
    'required': boolean;
    'single': boolean;
    'size': string;
    'stacked': boolean;
    'type': string|"checkbox"|"radio"|"radio-block"|"checkbox-block";
    'validate': () => Promise<FormResult>;
    'value': string|string[];
  }
  interface StellarToggleAttributes extends StencilHTMLAttributes {
    'card'?: any;
    'description'?: string;
    'flip'?: boolean;
    'label'?: string;
    'name'?: string;
    'novalidate'?: boolean;
    'onChange'?: (event: CustomEvent) => void;
    'required'?: boolean;
    'single'?: boolean;
    'size'?: string;
    'stacked'?: boolean;
    'type'?: string|"checkbox"|"radio"|"radio-block"|"checkbox-block";
    'value'?: string|string[];
  }

  interface StellarTooltip {
    'align': "left"|"center"|"right"|"middle-left"|"middle-center"|"middle-right"|"bottom-left"|"bottom-center"|"bottom-right";
  }
  interface StellarTooltipAttributes extends StencilHTMLAttributes {
    'align'?: "left"|"center"|"right"|"middle-left"|"middle-center"|"middle-right"|"bottom-left"|"bottom-center"|"bottom-right";
  }
}

declare global {
  interface StencilElementInterfaces {
    'StellarAccordion': Components.StellarAccordion;
    'StellarAsset': Components.StellarAsset;
    'WebAudioDebugger': Components.WebAudioDebugger;
    'WebAudioEffect': Components.WebAudioEffect;
    'WebAudioSequencer': Components.WebAudioSequencer;
    'WebAudioSource': Components.WebAudioSource;
    'WebAudioVisualizerShader': Components.WebAudioVisualizerShader;
    'WebAudioVisualizer': Components.WebAudioVisualizer;
    'WebAudio': Components.WebAudio;
    'StellarAvatar': Components.StellarAvatar;
    'StellarBlur': Components.StellarBlur;
    'StellarBreadcrumb': Components.StellarBreadcrumb;
    'StellarBreadcrumbs': Components.StellarBreadcrumbs;
    'StellarButton': Components.StellarButton;
    'StellarCallout': Components.StellarCallout;
    'StellarCard': Components.StellarCard;
    'StellarChart': Components.StellarChart;
    'StellarCode': Components.StellarCode;
    'StellarColorPicker': Components.StellarColorPicker;
    'StellarComment': Components.StellarComment;
    'StellarComments': Components.StellarComments;
    'StellarContent': Components.StellarContent;
    'CopyWrap': Components.CopyWrap;
    'StellarDropdown': Components.StellarDropdown;
    'StellarForm': Components.StellarForm;
    'StellarGrid': Components.StellarGrid;
    'StellarGroupOverflow': Components.StellarGroupOverflow;
    'StellarGroup': Components.StellarGroup;
    'StellarImage': Components.StellarImage;
    'StellarInput': Components.StellarInput;
    'StellarItem': Components.StellarItem;
    'StellarLabel': Components.StellarLabel;
    'StellarLayout': Components.StellarLayout;
    'Stellar360Image': Components.Stellar360Image;
    'Stellar360Video': Components.Stellar360Video;
    'StellarInterviewLine': Components.StellarInterviewLine;
    'StellarInterview': Components.StellarInterview;
    'SkeletonImg': Components.SkeletonImg;
    'SkeletonText': Components.SkeletonText;
    'StellarVideo': Components.StellarVideo;
    'StellarMessage': Components.StellarMessage;
    'StellarPagination': Components.StellarPagination;
    'StellarPasswordRequirements': Components.StellarPasswordRequirements;
    'StellarProgress': Components.StellarProgress;
    'StellarReveal': Components.StellarReveal;
    'StellarScatter': Components.StellarScatter;
    'StellarSelect': Components.StellarSelect;
    'StellarSlide': Components.StellarSlide;
    'StellarSlides': Components.StellarSlides;
    'StellarStep': Components.StellarStep;
    'StellarSteps': Components.StellarSteps;
    'StellarSwitch': Components.StellarSwitch;
    'StellarTab': Components.StellarTab;
    'StellarTable': Components.StellarTable;
    'StellarTabs': Components.StellarTabs;
    'StellarTag': Components.StellarTag;
    'StellarToggleOption': Components.StellarToggleOption;
    'StellarToggle': Components.StellarToggle;
    'StellarTooltip': Components.StellarTooltip;
  }

  interface StencilIntrinsicElements {
    'stellar-accordion': Components.StellarAccordionAttributes;
    'stellar-asset': Components.StellarAssetAttributes;
    'web-audio-debugger': Components.WebAudioDebuggerAttributes;
    'web-audio-effect': Components.WebAudioEffectAttributes;
    'web-audio-sequencer': Components.WebAudioSequencerAttributes;
    'web-audio-source': Components.WebAudioSourceAttributes;
    'web-audio-visualizer-shader': Components.WebAudioVisualizerShaderAttributes;
    'web-audio-visualizer': Components.WebAudioVisualizerAttributes;
    'web-audio': Components.WebAudioAttributes;
    'stellar-avatar': Components.StellarAvatarAttributes;
    'stellar-blur': Components.StellarBlurAttributes;
    'stellar-breadcrumb': Components.StellarBreadcrumbAttributes;
    'stellar-breadcrumbs': Components.StellarBreadcrumbsAttributes;
    'stellar-button': Components.StellarButtonAttributes;
    'stellar-callout': Components.StellarCalloutAttributes;
    'stellar-card': Components.StellarCardAttributes;
    'stellar-chart': Components.StellarChartAttributes;
    'stellar-code': Components.StellarCodeAttributes;
    'stellar-color-picker': Components.StellarColorPickerAttributes;
    'stellar-comment': Components.StellarCommentAttributes;
    'stellar-comments': Components.StellarCommentsAttributes;
    'stellar-content': Components.StellarContentAttributes;
    'copy-wrap': Components.CopyWrapAttributes;
    'stellar-dropdown': Components.StellarDropdownAttributes;
    'stellar-form': Components.StellarFormAttributes;
    'stellar-grid': Components.StellarGridAttributes;
    'stellar-group-overflow': Components.StellarGroupOverflowAttributes;
    'stellar-group': Components.StellarGroupAttributes;
    'stellar-image': Components.StellarImageAttributes;
    'stellar-input': Components.StellarInputAttributes;
    'stellar-item': Components.StellarItemAttributes;
    'stellar-label': Components.StellarLabelAttributes;
    'stellar-layout': Components.StellarLayoutAttributes;
    'stellar-360-image': Components.Stellar360ImageAttributes;
    'stellar-360-video': Components.Stellar360VideoAttributes;
    'stellar-interview-line': Components.StellarInterviewLineAttributes;
    'stellar-interview': Components.StellarInterviewAttributes;
    'skeleton-img': Components.SkeletonImgAttributes;
    'skeleton-text': Components.SkeletonTextAttributes;
    'stellar-video': Components.StellarVideoAttributes;
    'stellar-message': Components.StellarMessageAttributes;
    'stellar-pagination': Components.StellarPaginationAttributes;
    'stellar-password-requirements': Components.StellarPasswordRequirementsAttributes;
    'stellar-progress': Components.StellarProgressAttributes;
    'stellar-reveal': Components.StellarRevealAttributes;
    'stellar-scatter': Components.StellarScatterAttributes;
    'stellar-select': Components.StellarSelectAttributes;
    'stellar-slide': Components.StellarSlideAttributes;
    'stellar-slides': Components.StellarSlidesAttributes;
    'stellar-step': Components.StellarStepAttributes;
    'stellar-steps': Components.StellarStepsAttributes;
    'stellar-switch': Components.StellarSwitchAttributes;
    'stellar-tab': Components.StellarTabAttributes;
    'stellar-table': Components.StellarTableAttributes;
    'stellar-tabs': Components.StellarTabsAttributes;
    'stellar-tag': Components.StellarTagAttributes;
    'stellar-toggle-option': Components.StellarToggleOptionAttributes;
    'stellar-toggle': Components.StellarToggleAttributes;
    'stellar-tooltip': Components.StellarTooltipAttributes;
  }


  interface HTMLStellarAccordionElement extends Components.StellarAccordion, HTMLStencilElement {}
  var HTMLStellarAccordionElement: {
    prototype: HTMLStellarAccordionElement;
    new (): HTMLStellarAccordionElement;
  };

  interface HTMLStellarAssetElement extends Components.StellarAsset, HTMLStencilElement {}
  var HTMLStellarAssetElement: {
    prototype: HTMLStellarAssetElement;
    new (): HTMLStellarAssetElement;
  };

  interface HTMLWebAudioDebuggerElement extends Components.WebAudioDebugger, HTMLStencilElement {}
  var HTMLWebAudioDebuggerElement: {
    prototype: HTMLWebAudioDebuggerElement;
    new (): HTMLWebAudioDebuggerElement;
  };

  interface HTMLWebAudioEffectElement extends Components.WebAudioEffect, HTMLStencilElement {}
  var HTMLWebAudioEffectElement: {
    prototype: HTMLWebAudioEffectElement;
    new (): HTMLWebAudioEffectElement;
  };

  interface HTMLWebAudioSequencerElement extends Components.WebAudioSequencer, HTMLStencilElement {}
  var HTMLWebAudioSequencerElement: {
    prototype: HTMLWebAudioSequencerElement;
    new (): HTMLWebAudioSequencerElement;
  };

  interface HTMLWebAudioSourceElement extends Components.WebAudioSource, HTMLStencilElement {}
  var HTMLWebAudioSourceElement: {
    prototype: HTMLWebAudioSourceElement;
    new (): HTMLWebAudioSourceElement;
  };

  interface HTMLWebAudioVisualizerShaderElement extends Components.WebAudioVisualizerShader, HTMLStencilElement {}
  var HTMLWebAudioVisualizerShaderElement: {
    prototype: HTMLWebAudioVisualizerShaderElement;
    new (): HTMLWebAudioVisualizerShaderElement;
  };

  interface HTMLWebAudioVisualizerElement extends Components.WebAudioVisualizer, HTMLStencilElement {}
  var HTMLWebAudioVisualizerElement: {
    prototype: HTMLWebAudioVisualizerElement;
    new (): HTMLWebAudioVisualizerElement;
  };

  interface HTMLWebAudioElement extends Components.WebAudio, HTMLStencilElement {}
  var HTMLWebAudioElement: {
    prototype: HTMLWebAudioElement;
    new (): HTMLWebAudioElement;
  };

  interface HTMLStellarAvatarElement extends Components.StellarAvatar, HTMLStencilElement {}
  var HTMLStellarAvatarElement: {
    prototype: HTMLStellarAvatarElement;
    new (): HTMLStellarAvatarElement;
  };

  interface HTMLStellarBlurElement extends Components.StellarBlur, HTMLStencilElement {}
  var HTMLStellarBlurElement: {
    prototype: HTMLStellarBlurElement;
    new (): HTMLStellarBlurElement;
  };

  interface HTMLStellarBreadcrumbElement extends Components.StellarBreadcrumb, HTMLStencilElement {}
  var HTMLStellarBreadcrumbElement: {
    prototype: HTMLStellarBreadcrumbElement;
    new (): HTMLStellarBreadcrumbElement;
  };

  interface HTMLStellarBreadcrumbsElement extends Components.StellarBreadcrumbs, HTMLStencilElement {}
  var HTMLStellarBreadcrumbsElement: {
    prototype: HTMLStellarBreadcrumbsElement;
    new (): HTMLStellarBreadcrumbsElement;
  };

  interface HTMLStellarButtonElement extends Components.StellarButton, HTMLStencilElement {}
  var HTMLStellarButtonElement: {
    prototype: HTMLStellarButtonElement;
    new (): HTMLStellarButtonElement;
  };

  interface HTMLStellarCalloutElement extends Components.StellarCallout, HTMLStencilElement {}
  var HTMLStellarCalloutElement: {
    prototype: HTMLStellarCalloutElement;
    new (): HTMLStellarCalloutElement;
  };

  interface HTMLStellarCardElement extends Components.StellarCard, HTMLStencilElement {}
  var HTMLStellarCardElement: {
    prototype: HTMLStellarCardElement;
    new (): HTMLStellarCardElement;
  };

  interface HTMLStellarChartElement extends Components.StellarChart, HTMLStencilElement {}
  var HTMLStellarChartElement: {
    prototype: HTMLStellarChartElement;
    new (): HTMLStellarChartElement;
  };

  interface HTMLStellarCodeElement extends Components.StellarCode, HTMLStencilElement {}
  var HTMLStellarCodeElement: {
    prototype: HTMLStellarCodeElement;
    new (): HTMLStellarCodeElement;
  };

  interface HTMLStellarColorPickerElement extends Components.StellarColorPicker, HTMLStencilElement {}
  var HTMLStellarColorPickerElement: {
    prototype: HTMLStellarColorPickerElement;
    new (): HTMLStellarColorPickerElement;
  };

  interface HTMLStellarCommentElement extends Components.StellarComment, HTMLStencilElement {}
  var HTMLStellarCommentElement: {
    prototype: HTMLStellarCommentElement;
    new (): HTMLStellarCommentElement;
  };

  interface HTMLStellarCommentsElement extends Components.StellarComments, HTMLStencilElement {}
  var HTMLStellarCommentsElement: {
    prototype: HTMLStellarCommentsElement;
    new (): HTMLStellarCommentsElement;
  };

  interface HTMLStellarContentElement extends Components.StellarContent, HTMLStencilElement {}
  var HTMLStellarContentElement: {
    prototype: HTMLStellarContentElement;
    new (): HTMLStellarContentElement;
  };

  interface HTMLCopyWrapElement extends Components.CopyWrap, HTMLStencilElement {}
  var HTMLCopyWrapElement: {
    prototype: HTMLCopyWrapElement;
    new (): HTMLCopyWrapElement;
  };

  interface HTMLStellarDropdownElement extends Components.StellarDropdown, HTMLStencilElement {}
  var HTMLStellarDropdownElement: {
    prototype: HTMLStellarDropdownElement;
    new (): HTMLStellarDropdownElement;
  };

  interface HTMLStellarFormElement extends Components.StellarForm, HTMLStencilElement {}
  var HTMLStellarFormElement: {
    prototype: HTMLStellarFormElement;
    new (): HTMLStellarFormElement;
  };

  interface HTMLStellarGridElement extends Components.StellarGrid, HTMLStencilElement {}
  var HTMLStellarGridElement: {
    prototype: HTMLStellarGridElement;
    new (): HTMLStellarGridElement;
  };

  interface HTMLStellarGroupOverflowElement extends Components.StellarGroupOverflow, HTMLStencilElement {}
  var HTMLStellarGroupOverflowElement: {
    prototype: HTMLStellarGroupOverflowElement;
    new (): HTMLStellarGroupOverflowElement;
  };

  interface HTMLStellarGroupElement extends Components.StellarGroup, HTMLStencilElement {}
  var HTMLStellarGroupElement: {
    prototype: HTMLStellarGroupElement;
    new (): HTMLStellarGroupElement;
  };

  interface HTMLStellarImageElement extends Components.StellarImage, HTMLStencilElement {}
  var HTMLStellarImageElement: {
    prototype: HTMLStellarImageElement;
    new (): HTMLStellarImageElement;
  };

  interface HTMLStellarInputElement extends Components.StellarInput, HTMLStencilElement {}
  var HTMLStellarInputElement: {
    prototype: HTMLStellarInputElement;
    new (): HTMLStellarInputElement;
  };

  interface HTMLStellarItemElement extends Components.StellarItem, HTMLStencilElement {}
  var HTMLStellarItemElement: {
    prototype: HTMLStellarItemElement;
    new (): HTMLStellarItemElement;
  };

  interface HTMLStellarLabelElement extends Components.StellarLabel, HTMLStencilElement {}
  var HTMLStellarLabelElement: {
    prototype: HTMLStellarLabelElement;
    new (): HTMLStellarLabelElement;
  };

  interface HTMLStellarLayoutElement extends Components.StellarLayout, HTMLStencilElement {}
  var HTMLStellarLayoutElement: {
    prototype: HTMLStellarLayoutElement;
    new (): HTMLStellarLayoutElement;
  };

  interface HTMLStellar360ImageElement extends Components.Stellar360Image, HTMLStencilElement {}
  var HTMLStellar360ImageElement: {
    prototype: HTMLStellar360ImageElement;
    new (): HTMLStellar360ImageElement;
  };

  interface HTMLStellar360VideoElement extends Components.Stellar360Video, HTMLStencilElement {}
  var HTMLStellar360VideoElement: {
    prototype: HTMLStellar360VideoElement;
    new (): HTMLStellar360VideoElement;
  };

  interface HTMLStellarInterviewLineElement extends Components.StellarInterviewLine, HTMLStencilElement {}
  var HTMLStellarInterviewLineElement: {
    prototype: HTMLStellarInterviewLineElement;
    new (): HTMLStellarInterviewLineElement;
  };

  interface HTMLStellarInterviewElement extends Components.StellarInterview, HTMLStencilElement {}
  var HTMLStellarInterviewElement: {
    prototype: HTMLStellarInterviewElement;
    new (): HTMLStellarInterviewElement;
  };

  interface HTMLSkeletonImgElement extends Components.SkeletonImg, HTMLStencilElement {}
  var HTMLSkeletonImgElement: {
    prototype: HTMLSkeletonImgElement;
    new (): HTMLSkeletonImgElement;
  };

  interface HTMLSkeletonTextElement extends Components.SkeletonText, HTMLStencilElement {}
  var HTMLSkeletonTextElement: {
    prototype: HTMLSkeletonTextElement;
    new (): HTMLSkeletonTextElement;
  };

  interface HTMLStellarVideoElement extends Components.StellarVideo, HTMLStencilElement {}
  var HTMLStellarVideoElement: {
    prototype: HTMLStellarVideoElement;
    new (): HTMLStellarVideoElement;
  };

  interface HTMLStellarMessageElement extends Components.StellarMessage, HTMLStencilElement {}
  var HTMLStellarMessageElement: {
    prototype: HTMLStellarMessageElement;
    new (): HTMLStellarMessageElement;
  };

  interface HTMLStellarPaginationElement extends Components.StellarPagination, HTMLStencilElement {}
  var HTMLStellarPaginationElement: {
    prototype: HTMLStellarPaginationElement;
    new (): HTMLStellarPaginationElement;
  };

  interface HTMLStellarPasswordRequirementsElement extends Components.StellarPasswordRequirements, HTMLStencilElement {}
  var HTMLStellarPasswordRequirementsElement: {
    prototype: HTMLStellarPasswordRequirementsElement;
    new (): HTMLStellarPasswordRequirementsElement;
  };

  interface HTMLStellarProgressElement extends Components.StellarProgress, HTMLStencilElement {}
  var HTMLStellarProgressElement: {
    prototype: HTMLStellarProgressElement;
    new (): HTMLStellarProgressElement;
  };

  interface HTMLStellarRevealElement extends Components.StellarReveal, HTMLStencilElement {}
  var HTMLStellarRevealElement: {
    prototype: HTMLStellarRevealElement;
    new (): HTMLStellarRevealElement;
  };

  interface HTMLStellarScatterElement extends Components.StellarScatter, HTMLStencilElement {}
  var HTMLStellarScatterElement: {
    prototype: HTMLStellarScatterElement;
    new (): HTMLStellarScatterElement;
  };

  interface HTMLStellarSelectElement extends Components.StellarSelect, HTMLStencilElement {}
  var HTMLStellarSelectElement: {
    prototype: HTMLStellarSelectElement;
    new (): HTMLStellarSelectElement;
  };

  interface HTMLStellarSlideElement extends Components.StellarSlide, HTMLStencilElement {}
  var HTMLStellarSlideElement: {
    prototype: HTMLStellarSlideElement;
    new (): HTMLStellarSlideElement;
  };

  interface HTMLStellarSlidesElement extends Components.StellarSlides, HTMLStencilElement {}
  var HTMLStellarSlidesElement: {
    prototype: HTMLStellarSlidesElement;
    new (): HTMLStellarSlidesElement;
  };

  interface HTMLStellarStepElement extends Components.StellarStep, HTMLStencilElement {}
  var HTMLStellarStepElement: {
    prototype: HTMLStellarStepElement;
    new (): HTMLStellarStepElement;
  };

  interface HTMLStellarStepsElement extends Components.StellarSteps, HTMLStencilElement {}
  var HTMLStellarStepsElement: {
    prototype: HTMLStellarStepsElement;
    new (): HTMLStellarStepsElement;
  };

  interface HTMLStellarSwitchElement extends Components.StellarSwitch, HTMLStencilElement {}
  var HTMLStellarSwitchElement: {
    prototype: HTMLStellarSwitchElement;
    new (): HTMLStellarSwitchElement;
  };

  interface HTMLStellarTabElement extends Components.StellarTab, HTMLStencilElement {}
  var HTMLStellarTabElement: {
    prototype: HTMLStellarTabElement;
    new (): HTMLStellarTabElement;
  };

  interface HTMLStellarTableElement extends Components.StellarTable, HTMLStencilElement {}
  var HTMLStellarTableElement: {
    prototype: HTMLStellarTableElement;
    new (): HTMLStellarTableElement;
  };

  interface HTMLStellarTabsElement extends Components.StellarTabs, HTMLStencilElement {}
  var HTMLStellarTabsElement: {
    prototype: HTMLStellarTabsElement;
    new (): HTMLStellarTabsElement;
  };

  interface HTMLStellarTagElement extends Components.StellarTag, HTMLStencilElement {}
  var HTMLStellarTagElement: {
    prototype: HTMLStellarTagElement;
    new (): HTMLStellarTagElement;
  };

  interface HTMLStellarToggleOptionElement extends Components.StellarToggleOption, HTMLStencilElement {}
  var HTMLStellarToggleOptionElement: {
    prototype: HTMLStellarToggleOptionElement;
    new (): HTMLStellarToggleOptionElement;
  };

  interface HTMLStellarToggleElement extends Components.StellarToggle, HTMLStencilElement {}
  var HTMLStellarToggleElement: {
    prototype: HTMLStellarToggleElement;
    new (): HTMLStellarToggleElement;
  };

  interface HTMLStellarTooltipElement extends Components.StellarTooltip, HTMLStencilElement {}
  var HTMLStellarTooltipElement: {
    prototype: HTMLStellarTooltipElement;
    new (): HTMLStellarTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'stellar-accordion': HTMLStellarAccordionElement
    'stellar-asset': HTMLStellarAssetElement
    'web-audio-debugger': HTMLWebAudioDebuggerElement
    'web-audio-effect': HTMLWebAudioEffectElement
    'web-audio-sequencer': HTMLWebAudioSequencerElement
    'web-audio-source': HTMLWebAudioSourceElement
    'web-audio-visualizer-shader': HTMLWebAudioVisualizerShaderElement
    'web-audio-visualizer': HTMLWebAudioVisualizerElement
    'web-audio': HTMLWebAudioElement
    'stellar-avatar': HTMLStellarAvatarElement
    'stellar-blur': HTMLStellarBlurElement
    'stellar-breadcrumb': HTMLStellarBreadcrumbElement
    'stellar-breadcrumbs': HTMLStellarBreadcrumbsElement
    'stellar-button': HTMLStellarButtonElement
    'stellar-callout': HTMLStellarCalloutElement
    'stellar-card': HTMLStellarCardElement
    'stellar-chart': HTMLStellarChartElement
    'stellar-code': HTMLStellarCodeElement
    'stellar-color-picker': HTMLStellarColorPickerElement
    'stellar-comment': HTMLStellarCommentElement
    'stellar-comments': HTMLStellarCommentsElement
    'stellar-content': HTMLStellarContentElement
    'copy-wrap': HTMLCopyWrapElement
    'stellar-dropdown': HTMLStellarDropdownElement
    'stellar-form': HTMLStellarFormElement
    'stellar-grid': HTMLStellarGridElement
    'stellar-group-overflow': HTMLStellarGroupOverflowElement
    'stellar-group': HTMLStellarGroupElement
    'stellar-image': HTMLStellarImageElement
    'stellar-input': HTMLStellarInputElement
    'stellar-item': HTMLStellarItemElement
    'stellar-label': HTMLStellarLabelElement
    'stellar-layout': HTMLStellarLayoutElement
    'stellar-360-image': HTMLStellar360ImageElement
    'stellar-360-video': HTMLStellar360VideoElement
    'stellar-interview-line': HTMLStellarInterviewLineElement
    'stellar-interview': HTMLStellarInterviewElement
    'skeleton-img': HTMLSkeletonImgElement
    'skeleton-text': HTMLSkeletonTextElement
    'stellar-video': HTMLStellarVideoElement
    'stellar-message': HTMLStellarMessageElement
    'stellar-pagination': HTMLStellarPaginationElement
    'stellar-password-requirements': HTMLStellarPasswordRequirementsElement
    'stellar-progress': HTMLStellarProgressElement
    'stellar-reveal': HTMLStellarRevealElement
    'stellar-scatter': HTMLStellarScatterElement
    'stellar-select': HTMLStellarSelectElement
    'stellar-slide': HTMLStellarSlideElement
    'stellar-slides': HTMLStellarSlidesElement
    'stellar-step': HTMLStellarStepElement
    'stellar-steps': HTMLStellarStepsElement
    'stellar-switch': HTMLStellarSwitchElement
    'stellar-tab': HTMLStellarTabElement
    'stellar-table': HTMLStellarTableElement
    'stellar-tabs': HTMLStellarTabsElement
    'stellar-tag': HTMLStellarTagElement
    'stellar-toggle-option': HTMLStellarToggleOptionElement
    'stellar-toggle': HTMLStellarToggleElement
    'stellar-tooltip': HTMLStellarTooltipElement
  }

  interface ElementTagNameMap {
    'stellar-accordion': HTMLStellarAccordionElement;
    'stellar-asset': HTMLStellarAssetElement;
    'web-audio-debugger': HTMLWebAudioDebuggerElement;
    'web-audio-effect': HTMLWebAudioEffectElement;
    'web-audio-sequencer': HTMLWebAudioSequencerElement;
    'web-audio-source': HTMLWebAudioSourceElement;
    'web-audio-visualizer-shader': HTMLWebAudioVisualizerShaderElement;
    'web-audio-visualizer': HTMLWebAudioVisualizerElement;
    'web-audio': HTMLWebAudioElement;
    'stellar-avatar': HTMLStellarAvatarElement;
    'stellar-blur': HTMLStellarBlurElement;
    'stellar-breadcrumb': HTMLStellarBreadcrumbElement;
    'stellar-breadcrumbs': HTMLStellarBreadcrumbsElement;
    'stellar-button': HTMLStellarButtonElement;
    'stellar-callout': HTMLStellarCalloutElement;
    'stellar-card': HTMLStellarCardElement;
    'stellar-chart': HTMLStellarChartElement;
    'stellar-code': HTMLStellarCodeElement;
    'stellar-color-picker': HTMLStellarColorPickerElement;
    'stellar-comment': HTMLStellarCommentElement;
    'stellar-comments': HTMLStellarCommentsElement;
    'stellar-content': HTMLStellarContentElement;
    'copy-wrap': HTMLCopyWrapElement;
    'stellar-dropdown': HTMLStellarDropdownElement;
    'stellar-form': HTMLStellarFormElement;
    'stellar-grid': HTMLStellarGridElement;
    'stellar-group-overflow': HTMLStellarGroupOverflowElement;
    'stellar-group': HTMLStellarGroupElement;
    'stellar-image': HTMLStellarImageElement;
    'stellar-input': HTMLStellarInputElement;
    'stellar-item': HTMLStellarItemElement;
    'stellar-label': HTMLStellarLabelElement;
    'stellar-layout': HTMLStellarLayoutElement;
    'stellar-360-image': HTMLStellar360ImageElement;
    'stellar-360-video': HTMLStellar360VideoElement;
    'stellar-interview-line': HTMLStellarInterviewLineElement;
    'stellar-interview': HTMLStellarInterviewElement;
    'skeleton-img': HTMLSkeletonImgElement;
    'skeleton-text': HTMLSkeletonTextElement;
    'stellar-video': HTMLStellarVideoElement;
    'stellar-message': HTMLStellarMessageElement;
    'stellar-pagination': HTMLStellarPaginationElement;
    'stellar-password-requirements': HTMLStellarPasswordRequirementsElement;
    'stellar-progress': HTMLStellarProgressElement;
    'stellar-reveal': HTMLStellarRevealElement;
    'stellar-scatter': HTMLStellarScatterElement;
    'stellar-select': HTMLStellarSelectElement;
    'stellar-slide': HTMLStellarSlideElement;
    'stellar-slides': HTMLStellarSlidesElement;
    'stellar-step': HTMLStellarStepElement;
    'stellar-steps': HTMLStellarStepsElement;
    'stellar-switch': HTMLStellarSwitchElement;
    'stellar-tab': HTMLStellarTabElement;
    'stellar-table': HTMLStellarTableElement;
    'stellar-tabs': HTMLStellarTabsElement;
    'stellar-tag': HTMLStellarTagElement;
    'stellar-toggle-option': HTMLStellarToggleOptionElement;
    'stellar-toggle': HTMLStellarToggleElement;
    'stellar-tooltip': HTMLStellarTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
